package com.artesan.artesanapp.fragments

import android.net.Uri
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.Button
import android.widget.EditText
import android.widget.ImageView
import android.widget.Toast
import androidx.activity.result.contract.ActivityResultContracts
import androidx.fragment.app.Fragment
import com.artesan.artesanapp.R
import com.artesan.artesanapp.models.Product
import com.artesan.artesanapp.repositories.ProductRepository
import com.artesan.artesanapp.utils.ImageHelper

class CreateProductFragment : Fragment() {

    private lateinit var productRepository: ProductRepository
    private lateinit var editName: EditText
    private lateinit var editDescription: EditText
    private lateinit var editPrice: EditText
    private lateinit var editStock: EditText
    private lateinit var buttonCreate: Button
    private lateinit var buttonSelectImage: Button
    private lateinit var imagePreview: ImageView
    private var selectedImageBase64: String? = null

    // Image picker launcher
    private val imagePickerLauncher = registerForActivityResult(
        ActivityResultContracts.GetContent()
    ) { uri: Uri? ->
        uri?.let {
            handleImageSelection(it)
        }
    }

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return inflater.inflate(R.layout.fragment_create_product, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        productRepository = ProductRepository(requireContext())

        editName = view.findViewById(R.id.editProductName)
        editDescription = view.findViewById(R.id.editProductDescription)
        editPrice = view.findViewById(R.id.editProductPrice)
        editStock = view.findViewById(R.id.editProductStock)
        buttonCreate = view.findViewById(R.id.buttonCreateProduct)
        buttonSelectImage = view.findViewById(R.id.buttonSelectImage)
        imagePreview = view.findViewById(R.id.imagePreview)

        buttonCreate.setOnClickListener {
            createProduct()
        }

        buttonSelectImage.setOnClickListener {
            openImagePicker()
        }
    }

    private fun openImagePicker() {
        imagePickerLauncher.launch("image/*")
    }

    private fun handleImageSelection(uri: Uri) {
        selectedImageBase64 = ImageHelper.uriToBase64(requireContext(), uri)

        if (selectedImageBase64 != null) {
            val bitmap = ImageHelper.base64ToBitmap(selectedImageBase64!!)
            imagePreview.setImageBitmap(bitmap)
            Toast.makeText(requireContext(), "Imagen seleccionada", Toast.LENGTH_SHORT).show()
        } else {
            Toast.makeText(requireContext(), "Error al cargar la imagen", Toast.LENGTH_SHORT).show()
        }
    }

    private fun createProduct() {
        val name = editName.text.toString().trim()
        val description = editDescription.text.toString().trim()
        val priceText = editPrice.text.toString().trim()
        val stockText = editStock.text.toString().trim()

        // Validation
        if (name.isEmpty()) {
            Toast.makeText(requireContext(), "El nombre es requerido", Toast.LENGTH_SHORT).show()
            editName.requestFocus()
            return
        }

        if (description.isEmpty()) {
            Toast.makeText(requireContext(), "La descripción es requerida", Toast.LENGTH_SHORT).show()
            editDescription.requestFocus()
            return
        }

        val price = priceText.toDoubleOrNull()
        if (price == null || price <= 0) {
            Toast.makeText(requireContext(), "Ingrese un precio válido", Toast.LENGTH_SHORT).show()
            editPrice.requestFocus()
            return
        }

        val stock = stockText.toIntOrNull()
        if (stock == null || stock < 0) {
            Toast.makeText(requireContext(), "Ingrese un stock válido", Toast.LENGTH_SHORT).show()
            editStock.requestFocus()
            return
        }

        val product = Product(
            id = "", // Will be generated by repository
            name = name,
            description = description,
            price = price,
            stock = stock,
            imageBase64 = selectedImageBase64
        )

        productRepository.create(product)
            .onSuccess {
                Toast.makeText(requireContext(), "Producto creado exitosamente", Toast.LENGTH_SHORT).show()
                clearForm()
            }
            .onFailure { error ->
                Toast.makeText(requireContext(), error.message, Toast.LENGTH_SHORT).show()
            }
    }

    private fun clearForm() {
        editName.setText("")
        editDescription.setText("")
        editPrice.setText("")
        editStock.setText("")
        selectedImageBase64 = null
        imagePreview.setImageResource(android.R.drawable.ic_menu_gallery)
        editName.requestFocus()
    }
}
